services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: nephro-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost        # optional, for dev convenience
      KC_HOSTNAME_STRICT: "false"  # disables strict host validation
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8080"                 # maps container 8080 â†’ host 8180
    command: start-dev
